# Конфигурация ElytraMix
#
# Настройки сообщений -> messages.yml


# Стандартные значения для настройки сценариев
default-values:
  # Максимум 9 возможных вариантов
  integers: [1, 3, 5, 8, 10, 25, 50]
